### ISSUE TITLE
Can we have the bencode module as a library?

### ISSUE THREAD

**Issue by borkdude** [jasilven/redbush#1]
Hi!

For my [babashka](https://github.com/borkdude/babashka) project I needed a Rust bencode library which can read successive messages from stdin. I couldn't find a library, but I stumbled upon this nREPL-based project. So I ended up using your code here:

https://github.com/borkdude/babashka/tree/master/examples/pods/pod-babashka-filewatcher

Any chance you can expose the bencode stuff as a library? Right now I just downloaded the bencode module into my own repo...

**Comment by jasilven** [comment]
Hi! 
yes, sure I can do that.

**Comment by borkdude** [comment]
I'd love to use this as a crate! It's the only bencode lib I've found so far which allows streaming messages.

**Comment by jasilven** [comment]
yes I know, I also tried to find one but ended up writing it myself. Anyways, I'll try to find free timeslot to extract it to a separate lib for you.

**Comment by jasilven** [comment]
There it is now: https://github.com/jasilven/bencode_rs

It can be fetched for example like this (in Cargo.toml dependencies):
`bencode_rs = { git = "https://github.com/jasilven/bencode_rs", tag = "v0.1.0" }`

**Comment by borkdude** [comment]
@jasilven Thanks a lot! I'll try it out soon, but given that this is the same code as the module in your nREPL project, I expect it to just work. bencode_rs is not only a parser, but also a library to create bencode bytestrings right? The README doesn't emphasize this.

**Comment by jasilven** [comment]
Oh, yes right, it also generates bencode strings.

**Comment by borkdude** [comment]
@jasilven Confirming that it works as expected. Used in this project: https://github.com/babashka/pod-babashka-filewatcher.

**Comment by jasilven** [comment]
Great!
(I'll need to explore that babashka project of yours at some point, seems awesome!)
